import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';
const source=readFileSync(new URL('../lib/calculators.ts',import.meta.url),'utf8');
const exports={};
vm.runInNewContext(ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,{exports,require:()=>JSON.parse(readFileSync(new URL('../data/expertise.json',import.meta.url),'utf8'))});
const {expertiseTotal,validUpgrade,augmentTotal}=exports;
const full=category=>expertiseTotal([{id:'test',category,from:0,to:30}]);
assert.equal(full('weapon').steel,610);assert.equal(full('weapon').titanium,1030);assert.equal(full('weapon').receiver_components,1754);assert.equal(full('weapon').shd_calibration,76);assert.equal(full('weapon').field_recon_data,166);assert.equal(full('weapon').exotic_components,45);
assert.equal(full('gear').polycarbonate,305);assert.equal(full('gear').carbon_fiber,535);assert.equal(full('gear').protective_fabric,875);
assert.equal(full('skill').ceramics,770);assert.equal(full('skill').electronics,1300);assert.equal(full('skill').printer_filament,2200);assert.equal(full('skill').shd_calibration,90);assert.equal(full('skill').field_recon_data,204);
const step=expertiseTotal([{id:'step',category:'weapon',from:13,to:14}]);assert.equal(step.exotic_components,1);assert.equal(step.field_recon_data,5);assert.equal(step.shd_calibration,1);
assert.ok(Object.values(expertiseTotal([{id:'zero',category:'gear',from:20,to:20}])).every(n=>n===0));
assert.equal(expertiseTotal([{id:'a',category:'weapon',from:0,to:30},{id:'b',category:'skill',from:0,to:30}]).exotic_components,90);
for(const [from,to] of [[15,14],[-1,30],[0,31],[0,2.5],[NaN,30]])assert.equal(validUpgrade({id:'bad',category:'weapon',from,to}),false);
assert.throws(()=>expertiseTotal([{id:'bad',category:'weapon',from:20,to:10}]));
assert.equal(augmentTotal(4.3,7),30.1);assert.equal(augmentTotal(21.5,3),64.5);
console.log('PASS: screenshot totals, level boundaries, mixed items, invalid ranges and augment arithmetic.');
